version: '3'

services:
    
    api-rg-data-migration-prod:
        image: api-rg-data-migration-prod
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: api-rg-data-migration-prod
        restart: unless-stopped
        environment: 
            - RGDSN=${RGDSN}

# outer network to communicate with other services ----------------------------------------------------
networks:
    default:
        external:
            name: auth_proxy_network
    
