version: '3'

services:
    
    api-rg-data-migration-prod:
        image: api-rg-data-migration-prod
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: api-rg-data-migration-prod
        restart: unless-stopped
        volumes:
            - ./python:/usr/src/app

        environment: 
            - RGDSN=host=134.0.107.93 port=5432 dbname=rgdb user=root password=rosgas2011
        # command: python -u main.py
        command: sleep 5000

# outer network to communicate with other services ----------------------------------------------------
networks:
    default:
        external:
            name: auth_proxy_network
    
